const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'field-reports-registry.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newReports = `
  {
    id: 'fr-2026-td-01',
    title: 'Chenab Basin Hydrological Assessment - Winter 2026',
    source: 'Water Systems Authority',
    date: '2026-02-10',
    reportType: 'technical-report',
    pages: 56,
    status: 'reviewed',
    visibility: 'public',
    confidence: 'high',
    scope: 'Trans-Divisional',
    summary: 'Extensive flow rate and water quality assessment of the Chenab River tributaries. Identified decreased winter flow due to delayed snowmelt. Power generation forecasts have been adjusted accordingly.',
    districts: ['Doda', 'Kishtwar', 'Ramban'],
    entities: ['Chenab River', 'Baglihar Dam', 'Dul Hasti'],
    modules: ['Water Systems', 'Risk & Monitoring'],
    methods: ['Stream gauging', 'Water quality sampling'],
    previewAvailable: true,
    fileSize: '4.2 MB',
    methodology: 'Monthly gauge readings combined with automated telemetry station data.',
    lastUpdated: '2026-02-15',
    tags: ['chenab', 'hydrology', 'doda', 'kishtwar', 'water-systems', '2026'],
  },
  {
    id: 'fr-2026-td-02',
    title: 'Pir Panjal Leopard Corridor Survey',
    source: 'Wildlife Conservation Division',
    date: '2026-03-05',
    reportType: 'species-survey',
    pages: 32,
    status: 'field-verified',
    visibility: 'public',
    confidence: 'high',
    scope: 'Trans-Divisional',
    summary: 'Camera trap survey across the southern Pir Panjal range tracking common leopard movement. Identified two major corridors crossing the Mughal Road and increasing human-wildlife overlap.',
    districts: ['Poonch', 'Rajouri', 'Shopian'],
    entities: ['Common Leopard', 'Pir Panjal Range', 'Mughal Road'],
    modules: ['Biodiversity', 'Protected Areas'],
    methods: ['Camera trapping', 'Scat analysis'],
    previewAvailable: true,
    fileSize: '8.5 MB',
    methodology: 'Deployment of 120 motion-sensor camera traps over 45 days.',
    lastUpdated: '2026-03-10',
    tags: ['leopard', 'pir-panjal', 'poonch', 'rajouri', 'corridor', '2026'],
  },
  {
    id: 'fr-2026-td-03',
    title: 'Trikuta Hills Forest Fire Risk Model',
    source: 'Disaster Management Unit',
    date: '2026-04-02',
    reportType: 'risk-assessment',
    pages: 28,
    status: 'preliminary',
    visibility: 'public',
    confidence: 'moderate',
    scope: 'Trans-Divisional',
    summary: 'Pre-summer assessment of dry biomass and soil moisture anomalies in the lower Shivaliks and Trikuta Hills. Declared a moderate early-season fire risk for the Reasi-Udhampur belt.',
    districts: ['Reasi', 'Udhampur', 'Jammu'],
    entities: ['Trikuta Hills', 'Shivalik Range'],
    modules: ['Risk & Monitoring', 'Protected Areas'],
    methods: ['Satellite thermal imaging', 'Biomass sampling'],
    previewAvailable: true,
    fileSize: '2.1 MB',
    methodology: 'Analysis of MODIS thermal anomalies and ground truthing of pine litter depth.',
    lastUpdated: '2026-04-05',
    tags: ['fire-risk', 'reasi', 'udhampur', 'shivaliks', '2026'],
  },
  {
    id: 'fr-2026-tb-01',
    title: 'Transboundary Airshed Pollution Transport',
    source: 'EcoWatch Research Team',
    date: '2026-01-20',
    reportType: 'technical-report',
    pages: 45,
    status: 'reviewed',
    visibility: 'public',
    confidence: 'high',
    scope: 'Transboundary / Extended',
    summary: 'Analysis of transboundary particulate matter (PM2.5) movement across the LoC during winter inversion events. Traced agricultural burning and urban emissions flowing through the Jhelum gorge into the valley.',
    districts: ['Muzaffarabad', 'AJK', 'Baramulla', 'Kupwara'],
    entities: ['Jhelum Gorge', 'Winter Inversion Layer'],
    modules: ['Air & Noise Monitoring', 'Risk & Monitoring'],
    methods: ['Aerosol optical depth mapping', 'Wind trajectory modeling'],
    previewAvailable: true,
    fileSize: '5.5 MB',
    methodology: 'HYSPLIT back-trajectory modeling and Sentinel-5P TROPOMI data integration.',
    lastUpdated: '2026-01-25',
    tags: ['air-quality', 'transboundary', 'inversion', 'muzaffarabad', '2026'],
  },
  {
    id: 'fr-2026-tb-02',
    title: 'High Altitude Glacial Melt Rate - Karakoram / Ladakh',
    source: 'Cryosphere Research Institute',
    date: '2026-05-10',
    reportType: 'field-survey',
    pages: 80,
    status: 'reviewed',
    visibility: 'public',
    confidence: 'high',
    scope: 'Transboundary / Extended',
    summary: 'Joint assessment of glacial retreat in the extended Himalayan-Karakoram region. Measured abnormal mass loss in the Zanskar and Suru basins affecting downstream Indus water allocation.',
    districts: ['Leh', 'Kargil', 'Gilgit', 'Baltistan'],
    entities: ['Zanskar Range', 'Karakoram Glaciers', 'Indus Basin'],
    modules: ['Risk & Monitoring', 'Water Systems'],
    methods: ['LiDAR scanning', 'Ablation stake measurements'],
    previewAvailable: true,
    fileSize: '12.4 MB',
    methodology: 'Helicopter-borne LiDAR and extensive field camps measuring ablation stakes over 2 years.',
    lastUpdated: '2026-05-15',
    tags: ['glacier', 'ladakh', 'gilgit', 'baltistan', 'climate-change', '2026'],
  },
  {
    id: 'fr-2026-tb-03',
    title: 'Neelum-Jhelum Riparian Biodiversity Assessment',
    source: 'Environmental Protection Agency',
    date: '2026-03-25',
    reportType: 'environmental-impact',
    pages: 110,
    status: 'field-verified',
    visibility: 'public',
    confidence: 'high',
    scope: 'Transboundary / Extended',
    summary: 'Cross-border survey of riparian habitats along the Kishanganga/Neelum river. Highlighted impacts of hydroelectric dam water diversion on local aquatic species including the Brown Trout.',
    districts: ['Bandipora', 'Kupwara', 'Neelum', 'Muzaffarabad'],
    entities: ['Kishanganga River', 'Neelum River', 'Brown Trout'],
    modules: ['Biodiversity', 'Water Systems'],
    methods: ['Electro-fishing surveys', 'Habitat mapping'],
    previewAvailable: true,
    fileSize: '9.2 MB',
    methodology: 'Sampled 14 river reaches using standard electro-fishing and macroinvertebrate kick-netting protocols.',
    lastUpdated: '2026-03-28',
    tags: ['neelum', 'kishanganga', 'trout', 'hydroelectric', 'biodiversity', '2026'],
  },
  {
    id: 'fr-2026-td-04',
    title: 'Ranjit Sagar Dam Siltation Report',
    source: 'Water Systems Authority',
    date: '2026-04-15',
    reportType: 'monthly-bulletin',
    pages: 15,
    status: 'monthly-bulletin',
    visibility: 'public',
    confidence: 'moderate',
    scope: 'Trans-Divisional',
    summary: 'Quarterly bathymetric assessment of the Ranjit Sagar reservoir. Showed a 2% increase in sedimentation rates due to heavy upstream monsoon runoff in the Ravi basin.',
    districts: ['Kathua', 'Samba'],
    entities: ['Ranjit Sagar Dam', 'Ravi River'],
    modules: ['Water Systems'],
    methods: ['Bathymetric sonar mapping', 'Sediment coring'],
    previewAvailable: true,
    fileSize: '1.8 MB',
    methodology: 'Acoustic Doppler current profiling and sonar bathymetry.',
    lastUpdated: '2026-04-18',
    tags: ['ravi', 'kathua', 'sedimentation', 'water-systems', '2026'],
  },
  {
    id: 'fr-2026-tb-04',
    title: 'Snow Leopard Population Baseline - Deosai & Drass',
    source: 'Wildlife Conservation Division',
    date: '2026-02-28',
    reportType: 'species-survey',
    pages: 40,
    status: 'reviewed',
    visibility: 'restricted',
    confidence: 'high',
    scope: 'Transboundary / Extended',
    summary: 'Highly successful camera trapping mission tracking transboundary snow leopard populations moving between Deosai National Park and the Drass sector. Identified 8 distinct individuals.',
    districts: ['Kargil', 'Skardu', 'Baltistan'],
    entities: ['Snow Leopard', 'Deosai Plains', 'Drass Sector'],
    modules: ['Biodiversity', 'Protected Areas'],
    methods: ['Camera trapping', 'Genetic scat analysis'],
    previewAvailable: true,
    fileSize: '6.7 MB',
    methodology: 'Spatial Capture-Recapture (SCR) modeling using 85 camera stations.',
    lastUpdated: '2026-03-02',
    tags: ['snow-leopard', 'deosai', 'kargil', 'skardu', 'endangered', '2026'],
  },
`;

// Insert the new reports directly after 'export const fieldReportsRegistry: FieldReport[] = ['
content = content.replace(
  'export const fieldReportsRegistry: FieldReport[] = [',
  'export const fieldReportsRegistry: FieldReport[] = [' + newReports
);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully added Trans-Divisional and Transboundary reports!');
