const fs = require('fs');
const path = require('path');

const records = [
    // ─── MACRO J&K UT ───
    {
        id: 'stp-jk-macro-01',
        stp_name: 'J&K UT Total STP System',
        scope: 'All J&K',
        district: 'J&K UT',
        city_or_authority: 'UT-wide',
        category: 'Macro Infrastructure',
        capacity_mld: '129.19',
        operational_flow_mld: '73.64',
        technology: 'Multiple',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Various Basins',
        reuse_mld: '0.00',
        catchment_served: 'UT-wide',
        infrastructure_priority: 'Maximize Utilization',
        evidence_confidence: 'Verified Capacity',
        description: '16 STPs total. 129.19 MLD design capacity, but only 73.64 MLD is operational. Zero treated wastewater reuse.'
    },

    // ─── KASHMIR CORE STPS ───
    {
        id: 'stp-sgr-noor-01',
        stp_name: 'Noorbagh STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'UEED Srinagar',
        category: 'Major Municipal STP',
        capacity_mld: '60.00',
        operational_flow_mld: 'Commissioning',
        technology: 'Advanced',
        operational_status: 'Partial / Under Commissioning STP',
        receiving_waterbody_protected: 'Jhelum River',
        reuse_mld: '0.00',
        catchment_served: 'Greater Srinagar',
        infrastructure_priority: 'Complete Commissioning',
        evidence_confidence: 'Verified Capacity',
        description: 'Major city-wide STP in advanced commissioning stages to protect Jhelum River from downtown sewage.'
    },
    {
        id: 'stp-sgr-gupt-01',
        stp_name: 'Guptganga STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'UEED',
        category: 'Lake STP',
        capacity_mld: '30.00',
        operational_flow_mld: '0.00',
        technology: 'Advanced',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Dal Lake',
        reuse_mld: '0.00',
        catchment_served: 'Dal Lake Periphery',
        infrastructure_priority: 'Accelerate Construction',
        evidence_confidence: 'Planning Record',
        description: 'Under construction. Crucial for handling Dal Lake catchment wastewater.'
    },
    {
        id: 'stp-sgr-brari-01',
        stp_name: 'Brari Nambal STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'JKLCMA',
        category: 'Lake STP',
        capacity_mld: '17.08',
        operational_flow_mld: '16.10',
        technology: 'MBR',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Brari Nambal / Jhelum',
        reuse_mld: '0.00',
        catchment_served: 'Downtown Srinagar Core',
        infrastructure_priority: 'Upgrading & Compliance',
        evidence_confidence: 'Verified Capacity',
        description: 'Upgrading from 16.1 MLD. Frequently flagged by NGT for failing standards.'
    },
    {
        id: 'stp-sgr-allo-01',
        stp_name: 'Allochi Bagh STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'Srinagar',
        category: 'Municipal STP',
        capacity_mld: '14.00',
        operational_flow_mld: '0.00',
        technology: 'Proposed',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Doodh Ganga / Jhelum',
        reuse_mld: '0.00',
        catchment_served: 'Allochi Bagh / Solina',
        infrastructure_priority: 'Tendering',
        evidence_confidence: 'Planning Record',
        description: 'Recently cleared by High Court to treat Doodh Ganga outfalls.'
    },
    {
        id: 'stp-sgr-amir-01',
        stp_name: 'Nallah Amir Khan STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'JKLCMA',
        category: 'Lake STP',
        capacity_mld: '5.40',
        operational_flow_mld: '5.40',
        technology: 'MBR',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Nallah Amir Khan / Nigeen',
        reuse_mld: '0.00',
        catchment_served: 'Nigeen Inter-connecting belt',
        infrastructure_priority: 'Maintenance',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-sgr-hzb-01',
        stp_name: 'Hazratbal STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'JKLCMA',
        category: 'Lake STP',
        capacity_mld: '7.50',
        operational_flow_mld: '7.50',
        technology: 'MBR',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Dal Lake',
        reuse_mld: '0.00',
        catchment_served: 'Dal Lake North',
        infrastructure_priority: 'Optimize Flow',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-sgr-lam-01',
        stp_name: 'Laam / Nishat STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'JKLCMA',
        category: 'Lake STP',
        capacity_mld: '4.50',
        operational_flow_mld: '4.50',
        technology: 'MBR',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Dal Lake',
        reuse_mld: '0.00',
        catchment_served: 'Dal Lake East',
        infrastructure_priority: 'Optimize Flow',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-sgr-habak-01',
        stp_name: 'Habak STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'JKLCMA',
        category: 'Lake STP',
        capacity_mld: '3.20',
        operational_flow_mld: '3.20',
        technology: 'MBR',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Dal Lake',
        reuse_mld: '0.00',
        catchment_served: 'Dal Lake North-West',
        infrastructure_priority: 'Optimize Flow',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-sgr-chat-01',
        stp_name: 'Chattabal STP',
        scope: 'Kashmir Core',
        district: 'Srinagar',
        city_or_authority: 'Srinagar',
        category: 'Municipal STP',
        capacity_mld: '2.50',
        operational_flow_mld: '0.00',
        technology: 'Proposed',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Jhelum River',
        reuse_mld: '0.00',
        catchment_served: 'Chattabal Area',
        infrastructure_priority: 'Construction Phase',
        evidence_confidence: 'Project-Reported Capacity',
        description: 'Foundation laid to address local Jhelum river outfalls.'
    },
    {
        id: 'stp-bud-doodh-01',
        stp_name: 'Doodh Ganga Modular STPs',
        scope: 'Kashmir Core',
        district: 'Budgam',
        city_or_authority: 'Budgam / Srinagar',
        category: 'Modular STP Network',
        capacity_mld: '12.25',
        operational_flow_mld: '0.00',
        technology: 'Modular',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Doodh Ganga / Jhelum',
        reuse_mld: '0.00',
        catchment_served: 'Doodh Ganga catchment',
        infrastructure_priority: 'High - NGT Mandated',
        evidence_confidence: 'Planning Record',
        description: 'Proposed after NGT imposed a Rs 35 crore penalty for untreated outfalls.'
    },
    {
        id: 'stp-ant-meh-01',
        stp_name: 'Mehandi Kadal STP',
        scope: 'Kashmir Core',
        district: 'Anantnag',
        city_or_authority: 'Anantnag Municipal Council',
        category: 'Municipal STP',
        capacity_mld: '4.00',
        operational_flow_mld: 'Unknown',
        technology: 'ASP',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Jhelum Tributaries',
        reuse_mld: '0.00',
        catchment_served: 'Anantnag Town',
        infrastructure_priority: 'Network Linkage',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-bla-01',
        stp_name: 'Baramulla Town STP',
        scope: 'Kashmir Core',
        district: 'Baramulla',
        city_or_authority: 'Baramulla',
        category: 'Municipal STP',
        capacity_mld: 'Unknown (Rs 40 Cr)',
        operational_flow_mld: '0.00',
        technology: 'Proposed',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Jhelum River',
        reuse_mld: '0.00',
        catchment_served: 'Baramulla Town',
        infrastructure_priority: 'Construction Phase',
        evidence_confidence: 'Project-Reported Capacity'
    },

    // ─── TRANS-DIVISIONAL STPS (JAMMU, LADAKH, ETC) ───
    {
        id: 'stp-jmu-bhg-27',
        stp_name: 'Bhagwati Nagar STP',
        scope: 'Trans-Divisional',
        district: 'Jammu',
        city_or_authority: 'JMC / UEED',
        category: 'Major Municipal STP',
        capacity_mld: '27.00',
        operational_flow_mld: 'Partial',
        technology: 'ASP',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Tawi River',
        reuse_mld: '0.00',
        catchment_served: 'Jammu West / Bhagwati Nagar',
        infrastructure_priority: 'Full Commissioning & Testing',
        evidence_confidence: 'Verified Capacity',
        description: 'Operational but undergoing upgrades for full functionality and JKPCC compliance.'
    },
    {
        id: 'stp-jmu-rakh-01',
        stp_name: 'Rakh Raipur / Belicharana STP',
        scope: 'Trans-Divisional',
        district: 'Jammu',
        city_or_authority: 'UEED',
        category: 'Municipal STP',
        capacity_mld: '4.00',
        operational_flow_mld: 'Unknown',
        technology: 'Unknown',
        operational_status: 'Partial / Under Commissioning STP',
        receiving_waterbody_protected: 'Tawi River Basin',
        reuse_mld: '0.00',
        catchment_served: 'Belicharana Area',
        infrastructure_priority: 'Resolve Consent to Operate',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-udh-dev-01',
        stp_name: 'Devika STP 1',
        scope: 'Trans-Divisional',
        district: 'Udhampur',
        city_or_authority: 'UEED',
        category: 'River Rejuvenation STP',
        capacity_mld: '8.00',
        operational_flow_mld: '0.00',
        technology: 'Unknown',
        operational_status: 'Partial / Under Commissioning STP',
        receiving_waterbody_protected: 'Devika River',
        reuse_mld: '0.00',
        catchment_served: 'Udhampur Town Zone 1',
        infrastructure_priority: 'NGT Monitored Acceleration',
        evidence_confidence: 'Verified Capacity',
        description: 'Part of the 13.6 MLD Devika River Rejuvenation Project.'
    },
    {
        id: 'stp-udh-dev-02',
        stp_name: 'Devika STP 2',
        scope: 'Trans-Divisional',
        district: 'Udhampur',
        city_or_authority: 'UEED',
        category: 'River Rejuvenation STP',
        capacity_mld: '4.00',
        operational_flow_mld: 'Partial',
        technology: 'Unknown',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Devika River',
        reuse_mld: '0.00',
        catchment_served: 'Udhampur Town Zone 2',
        infrastructure_priority: 'Install SCADA / Automation',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-udh-dev-03',
        stp_name: 'Devika STP 3',
        scope: 'Trans-Divisional',
        district: 'Udhampur',
        city_or_authority: 'UEED',
        category: 'River Rejuvenation STP',
        capacity_mld: '1.60',
        operational_flow_mld: 'Partial',
        technology: 'Unknown',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Devika River',
        reuse_mld: '0.00',
        catchment_served: 'Udhampur Town Zone 3',
        infrastructure_priority: 'Commissioning Issues',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-raj-01',
        stp_name: 'Rajouri Municipal Council STP',
        scope: 'Trans-Divisional',
        district: 'Rajouri',
        city_or_authority: 'Rajouri',
        category: 'Municipal STP',
        capacity_mld: '4.50',
        operational_flow_mld: '0.00',
        technology: 'SBR',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Local River / Streams',
        reuse_mld: '0.00',
        catchment_served: 'Rajouri Town',
        infrastructure_priority: 'Tendering (SBM 2.0)',
        evidence_confidence: 'Planning Record',
        description: 'Approved mid-2026 as part of a 34.43 cr project.'
    },
    {
        id: 'stp-pnch-01',
        stp_name: 'Poonch Municipal Council STP',
        scope: 'Trans-Divisional',
        district: 'Poonch',
        city_or_authority: 'Poonch',
        category: 'Municipal STP',
        capacity_mld: '4.50',
        operational_flow_mld: '0.00',
        technology: 'SBR',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Poonch River',
        reuse_mld: '0.00',
        catchment_served: 'Poonch Town',
        infrastructure_priority: 'Tendering (SBM 2.0)',
        evidence_confidence: 'Planning Record'
    },
    {
        id: 'stp-kth-lakh-01',
        stp_name: 'Lakhanpur Cluster STP',
        scope: 'Trans-Divisional',
        district: 'Kathua',
        city_or_authority: 'Kathua',
        category: 'Municipal STP',
        capacity_mld: '8.50',
        operational_flow_mld: '0.00',
        technology: 'Unknown',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Ravi River Basin',
        reuse_mld: '0.00',
        catchment_served: 'Lakhanpur Cluster',
        infrastructure_priority: 'Technical Evaluation',
        evidence_confidence: 'Planning Record'
    },
    {
        id: 'stp-leh-cen-01',
        stp_name: 'Leh Central STP',
        scope: 'Trans-Divisional',
        district: 'Leh',
        city_or_authority: 'Leh Municipality',
        category: 'Municipal STP',
        capacity_mld: '3.00',
        operational_flow_mld: '3.00',
        technology: 'Unknown',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Indus River Basin (Groundwater)',
        reuse_mld: '0.00',
        catchment_served: 'Leh Central Town',
        infrastructure_priority: 'Capacity Expansion',
        evidence_confidence: 'Verified Capacity'
    },
    {
        id: 'stp-leh-dstp-01',
        stp_name: 'Leh DSTP Project',
        scope: 'Trans-Divisional',
        district: 'Leh',
        city_or_authority: 'Leh Administration',
        category: 'Decentralized STP',
        capacity_mld: 'Unknown',
        operational_flow_mld: '0.00',
        technology: 'Decentralized',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Indus River Basin',
        reuse_mld: '0.00',
        catchment_served: 'Leh Periphery',
        infrastructure_priority: 'Construction',
        evidence_confidence: 'Project-Reported Capacity',
        description: '9.12 crore budget approved June 2026 for point-of-generation treatment.'
    },
    {
        id: 'stp-dod-01',
        stp_name: 'Doda Proposed STP',
        scope: 'Trans-Divisional',
        district: 'Doda',
        city_or_authority: 'UEED',
        category: 'Municipal STP',
        capacity_mld: '4.50',
        operational_flow_mld: '0.00',
        technology: 'Unknown',
        operational_status: 'Planned STP',
        receiving_waterbody_protected: 'Chenab River',
        reuse_mld: '0.00',
        catchment_served: 'Doda Town',
        infrastructure_priority: 'Mitigate Land Subsidence',
        evidence_confidence: 'Planning Record',
        description: 'Proposed to halt severe seepage causing land subsidence.'
    },

    // ─── TRANSBOUNDARY (AJK & GB) ───
    {
        id: 'stp-ajk-muz-01',
        stp_name: 'Muzaffarabad Municipal STP',
        scope: 'Transboundary / Extended',
        district: 'Muzaffarabad',
        city_or_authority: 'Muzaffarabad',
        category: 'Municipal STP',
        capacity_mld: '0.00',
        operational_flow_mld: '0.00',
        technology: 'None',
        operational_status: 'No Public STP Record Found',
        receiving_waterbody_protected: 'Neelum / Jhelum',
        reuse_mld: '0.00',
        catchment_served: 'Muzaffarabad City',
        infrastructure_priority: 'Master Plan Implementation',
        evidence_confidence: 'Public Data Gap',
        description: 'No large-scale STP. Neelum-Jhelum Hydropower STP commitments remain unfulfilled.'
    },
    {
        id: 'stp-ajk-mir-01',
        stp_name: 'Mirpur Pearl Continental STP',
        scope: 'Transboundary / Extended',
        district: 'Mirpur',
        city_or_authority: 'Private / Commercial',
        category: 'Commercial STP',
        capacity_mld: '0.15',
        operational_flow_mld: '0.15',
        technology: 'Compact',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Mangla Reservoir',
        reuse_mld: '0.10',
        catchment_served: 'Hotel Complex',
        infrastructure_priority: 'Private Maintenance',
        evidence_confidence: 'Project-Reported Capacity'
    },
    {
        id: 'stp-gb-glt-01',
        stp_name: 'Gilgit City STP',
        scope: 'Transboundary / Extended',
        district: 'Gilgit',
        city_or_authority: 'Gilgit Development Authority (GDA)',
        category: 'Major Municipal STP',
        capacity_mld: '18.18',
        operational_flow_mld: '0.00',
        technology: 'Mechanical Activated Sludge',
        operational_status: 'Partial / Under Commissioning STP',
        receiving_waterbody_protected: 'Gilgit River',
        reuse_mld: '0.00',
        catchment_served: 'Baseen, Bab-e-Gilgit, Konodas',
        infrastructure_priority: 'Electro-mechanical Phase',
        evidence_confidence: 'Project-Reported Capacity',
        description: '4 MGPD capacity. 90% progress in 2026. Includes 209km of sewer pipelines.'
    },
    {
        id: 'stp-gb-hun-01',
        stp_name: 'Attabad Lake Zone',
        scope: 'Transboundary / Extended',
        district: 'Hunza',
        city_or_authority: 'GB-EPA',
        category: 'Tourism Hub',
        capacity_mld: '0.00',
        operational_flow_mld: '0.00',
        technology: 'Soakage Pits (Failing)',
        operational_status: 'No Public STP Record Found',
        receiving_waterbody_protected: 'Attabad Lake',
        reuse_mld: '0.00',
        catchment_served: 'Resort Network',
        infrastructure_priority: 'Moratorium Enforced',
        evidence_confidence: 'Verified Capacity',
        description: 'Unregulated resorts dumping raw sewage. GB-EPA imposed a 5-year construction moratorium.'
    },
    {
        id: 'stp-gb-hun-02',
        stp_name: 'Hunza Green STPs',
        scope: 'Transboundary / Extended',
        district: 'Hunza',
        city_or_authority: 'AKAH / Community',
        category: 'Decentralized STP',
        capacity_mld: 'Unknown',
        operational_flow_mld: 'Active',
        technology: 'Nature-based (Trees/Aquatic)',
        operational_status: 'Operational STP',
        receiving_waterbody_protected: 'Local Streams / Hunza River',
        reuse_mld: 'Unknown',
        catchment_served: 'Select Villages',
        infrastructure_priority: 'Scale up model',
        evidence_confidence: 'Project-Reported Capacity'
    }
];

let out = "export type Scope = 'All J&K' | 'Kashmir Core' | 'Trans-Divisional' | 'Transboundary / Extended';\n\n";
out += "export interface STPRecord {\n";
out += "  id: string;\n";
out += "  stp_name: string;\n";
out += "  scope: Scope;\n";
out += "  district: string;\n";
out += "  city_or_authority: string;\n";
out += "  category: string;\n";
out += "  capacity_mld: string;\n";
out += "  operational_flow_mld: string;\n";
out += "  technology: string;\n";
out += "  operational_status: 'Operational STP' | 'Partial / Under Commissioning STP' | 'Planned STP' | 'No Public STP Record Found';\n";
out += "  receiving_waterbody_protected: string;\n";
out += "  reuse_mld: string;\n";
out += "  catchment_served: string;\n";
out += "  infrastructure_priority: string;\n";
out += "  evidence_confidence: 'Verified Capacity' | 'Project-Reported Capacity' | 'Planning Record' | 'Public Data Gap' | 'Research Verified';\n";
out += "  source_url?: string;\n";
out += "  description?: string;\n";
out += "}\n\n";
out += "export const stpData: STPRecord[] = " + JSON.stringify(records, null, 2) + ";\n";

fs.writeFileSync(path.join(__dirname, '../src/data/stp-infrastructure.ts'), out);
console.log('Successfully generated stp-infrastructure.ts with ' + records.length + ' records based on 2026 intelligence.');
